version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
  pre_build:
    commands:
      - npm test
  build:
    commands:
      - npm run build:prod
  post_build:
    commands:
      - aws s3 sync --delete public s3://base-converter
